# Importar Biblioteca

In [1]:
import duckdb

# Conexão com DuckDB

In [2]:
conexao = duckdb.connect('../dados/filme_duckdb.db')

# Listar todas as tabelas do BD

In [3]:
query = " SHOW TABLES "
resultado = conexao.execute(query).fetchall()
print(resultado)

[('countries',), ('directors',), ('filmes',), ('filmes_countries',), ('filmes_directors',), ('filmes_genres',), ('filmes_imdb',), ('filmes_languages',), ('filmes_locations',), ('filmes_stars',), ('filmes_writers',), ('genres',), ('languages',), ('locations',), ('stars',), ('writers',)]

# Listar dados originais

In [22]:
query = 'SELECT * FROM filmes_imdb;'
df = conexao.execute(query).fetchdf()
df.head(5)

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt0073195,Jaws,https://www.imdb.com/title/tt0073195,1975,2h 4m,PG,8.1,683K,7000000.0,477220580.0,...,"['Peter Benchley', 'Carl Gottlieb']","['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'...",['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...",['English'],0,20,0
1,tt0073629,The Rocky Horror Picture Show,https://www.imdb.com/title/tt0073629,1975,1h 40m,R,7.4,173K,1200000.0,115798478.0,...,"[""Richard O'Brien"", 'Jim Sharman']","['Tim Curry', 'Susan Sarandon', 'Barry Bostwick']","['Dark Comedy', 'Raunchy Comedy', 'Rock Musica...","['United Kingdom', 'United States']","['Oakley Court, Windsor Road, Oakley Green, Wi...","['Twentieth Century Fox', 'Michael White Produ...",['English'],0,4,0
2,tt0073486,One Flew Over the Cuckoo's Nest,https://www.imdb.com/title/tt0073486,1975,2h 13m,R,8.7,1.1M,3000000.0,109115366.0,...,"['Lawrence Hauben', 'Bo Goldman', 'Ken Kesey']","['Jack Nicholson', 'Louise Fletcher', 'Michael...","['Medical Drama', 'Psychological Drama', 'Drama']",['United States'],['Oregon State Mental Hospital - 2600 Center S...,"['Fantasy Films', 'N.V. Zvaluw']",['English'],0,15,0
3,tt0072890,Dog Day Afternoon,https://www.imdb.com/title/tt0072890,1975,2h 5m,R,8.0,279K,1800000.0,50002721.0,...,"['Frank Pierson', 'P.F. Kluge', 'Thomas Moore']","['Al Pacino', 'John Cazale', 'Penelope Allen']","['Heist', 'True Crime', 'Biography', 'Crime', ...",['United States'],"['285 Prospect Park West, Brooklyn, New York C...","['Warner Bros.', 'Artists Entertainment Complex']",['English'],0,20,0
4,tt0073692,Shampoo,https://www.imdb.com/title/tt0073692,1975,1h 50m,R,6.4,15K,4000000.0,49407734.0,...,"['Robert Towne', 'Warren Beatty']","['Warren Beatty', 'Julie Christie', 'Goldie Ha...","['Satire', 'Comedy', 'Drama']",['United States'],"['2270 Bowmont Drive, Beverly Hills, Californi...","['Persky-Bright / Vista', 'Columbia Pictures',...",['English'],0,11,0

In [9]:
# descrição dos dados
df.describe()

,Year,Rating,budget,grossWorldWide,gross_US_Canada,opening_weekend_Gross,wins,nominations,oscars
count,33600.000000,33462.000000,1.181500e+04,1.822200e+04,1.757100e+04,1.552300e+04,33600.0,33600.000000,33600.000000
mean,1992.393631,6.155158,8.454320e+07,3.814961e+07,1.808236e+07,5.110082e+06,0.0,4.850357,0.102619
std,18.957395,1.146070,2.866281e+09,1.210105e+08,4.853181e+07,1.488319e+07,0.0,17.719188,0.508687
min,1960.000000,1.100000,1.000000e+00,1.000000e+00,6.400000e+01,1.100000e+01,0.0,0.000000,0.000000
25%,1976.000000,5.500000,2.000000e+06,1.589938e+05,8.603650e+04,1.399650e+04,0.0,0.000000,0.000000
50%,1993.000000,6.300000,9.000000e+06,2.311544e+06,9.094110e+05,1.075360e+05,0.0,0.000000,0.000000
75%,2009.000000,7.000000,2.700000e+07,2.092931e+07,1.405137e+07,3.772558e+06,0.0,3.000000,0.000000
max,2024.000000,9.600000,3.000000e+11,2.923706e+09,9.366622e+08,3.571150e+08,0.0,433.000000,11.000000

In [8]:
# informações sobre os dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33600 entries, 0 to 33599
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     33600 non-null  object
 1   Title                  33600 non-null  object
 2   Movie Link             33600 non-null  object
 3   Year                   33600 non-null  int64
 4   Duration               33379 non-null  object
 5   MPA                    25624 non-null  object
 6   Rating                 33462 non-null  float64
 7   Votes                  33462 non-null  object
 8   budget                 11815 non-null  float64
 9   grossWorldWide         18222 non-null  float64
 10  gross_US_Canada        17571 non-null  float64
 11  opening_weekend_Gross  15523 non-null  float64
 12  directors              33241 non-null  object
 13  writers                32024 non-null  object
 14  stars                  33127 non-null  object
 15  genres                 33218 non-null  object
 16  countries_origin       33234 non-null  object
 17  filming_locations      26871 non-null  object
 18  production_companies   32222 non-null  object
 19  Languages              33126 non-null  object
 20  wins                   33600 non-null  int64
 21  nominations            33600 non-null  int64
 22  oscars                 33600 non-null  int64
dtypes: float64(5), int64(4), object(14)
memory usage: 5.9+ MB

In [10]:
# nome das colunas
df.columns

Index(['id', 'Title', 'Movie Link', 'Year', 'Duration', 'MPA', 'Rating',
       'Votes', 'budget', 'grossWorldWide', 'gross_US_Canada',
       'opening_weekend_Gross', 'directors', 'writers', 'stars', 'genres',
       'countries_origin', 'filming_locations', 'production_companies',
       'Languages', 'wins', 'nominations', 'oscars'],
      dtype='object')

In [11]:
# quantidade de linhas e colunas
df.shape

(33600, 23)

In [12]:
#Filtrando dados
# SELECT * FROM filmes_imdb WHERE Votes = '279K';
df_filtrado = df[df['Votes'] == '279K']
df_filtrado

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
3,tt0072890,Dog Day Afternoon,https://www.imdb.com/title/tt0072890,1975,2h 5m,R,8.0,279K,1800000.0,50002721.0,...,"['Frank Pierson', 'P.F. Kluge', 'Thomas Moore']","['Al Pacino', 'John Cazale', 'Penelope Allen']","['Heist', 'True Crime', 'Biography', 'Crime', ...",['United States'],"['285 Prospect Park West, Brooklyn, New York C...","['Warner Bros.', 'Artists Entertainment Complex']",['English'],0,20,0
2714,tt1931533,Seven Psychopaths,https://www.imdb.com/title/tt1931533,2012,1h 50m,R,7.1,279K,15000000.0,29347202.0,...,['Martin McDonagh'],"['Colin Farrell', 'Woody Harrelson', 'Sam Rock...","['Caper', 'Dark Comedy', 'Gangster', 'Serial K...","['United Kingdom', 'United States']","['Joshua Tree National Park, California, USA']","['CBS Films', 'Film4', 'British Film Institute...","['English', 'Vietnamese']",0,21,1
6250,tt0363547,Dawn of the Dead,https://www.imdb.com/title/tt0363547,2004,1h 41m,R,7.2,279K,26000000.0,102280154.0,...,"['George A. Romero', 'James Gunn']","['Sarah Polley', 'Ving Rhames', 'Mekhi Phifer']","['Supernatural Horror', 'Survival', 'Zombie Ho...","['United States', 'Canada', 'Japan', 'France']","['Thornhill Square Mall, Thornhill, Ontario, C...","['Strike Entertainment', 'New Amsterdam Entert...",['English'],0,17,0
8955,tt0102057,Hook,https://www.imdb.com/title/tt0102057,1991,2h 22m,PG,6.8,279K,70000000.0,300854823.0,...,"['J.M. Barrie', 'James V. Hart', 'Nick Castle']","['Dustin Hoffman', 'Robin Williams', 'Julia Ro...","['Fairy Tale', 'Parody', 'Swashbuckler', 'Adve...",['United States'],"[""Kaua'i, Hawaii, USA""]","['TriStar Pictures', 'Amblin Entertainment', '...",['English'],0,24,5
21225,tt0327597,Coraline,https://www.imdb.com/title/tt0327597,2009,1h 40m,PG,7.8,279K,60000000.0,185860104.0,...,"['Henry Selick', 'Neil Gaiman']","['Dakota Fanning', 'Teri Hatcher', 'John Hodgm...","['Dark Fantasy', 'Stop Motion Animation', 'Sup...","['United States', 'Austria', 'France', 'Hungary']","['Portland, Oregon, USA']","['Focus Features', 'Laika Entertainment', 'Pan...","['English', 'Russian']",0,46,1
22752,tt7097896,Venom: Let There Be Carnage,https://www.imdb.com/title/tt7097896,2021,1h 37m,PG-13,5.9,279K,110000000.0,506813864.0,...,"['Kelly Marcel', 'Tom Hardy']","['Tom Hardy', 'Woody Harrelson', 'Michelle Wil...","['Kaiju', 'One-Person Army Action', 'Superhero...",['United States'],"['London, England, UK']","['Columbia Pictures', 'Marvel Entertainment', ...","['English', 'Spanish', 'Mandarin', 'Japanese']",0,6,0

# Consultas do arquivo query.sql

### Consultar filmes genero drama

In [14]:
query = "SELECT * FROM filmes_imdb WHERE genres LIKE '%Drama%'"
df_drama = conexao.execute(query).fetchdf()
df_drama.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt0073195,Jaws,https://www.imdb.com/title/tt0073195,1975,2h 4m,PG,8.1,683K,7000000.0,477220580.0,...,"['Peter Benchley', 'Carl Gottlieb']","['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'...",['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...",['English'],0,20,0
1,tt0073486,One Flew Over the Cuckoo's Nest,https://www.imdb.com/title/tt0073486,1975,2h 13m,R,8.7,1.1M,3000000.0,109115366.0,...,"['Lawrence Hauben', 'Bo Goldman', 'Ken Kesey']","['Jack Nicholson', 'Louise Fletcher', 'Michael...","['Medical Drama', 'Psychological Drama', 'Drama']",['United States'],['Oregon State Mental Hospital - 2600 Center S...,"['Fantasy Films', 'N.V. Zvaluw']",['English'],0,15,0
2,tt0072890,Dog Day Afternoon,https://www.imdb.com/title/tt0072890,1975,2h 5m,R,8.0,279K,1800000.0,50002721.0,...,"['Frank Pierson', 'P.F. Kluge', 'Thomas Moore']","['Al Pacino', 'John Cazale', 'Penelope Allen']","['Heist', 'True Crime', 'Biography', 'Crime', ...",['United States'],"['285 Prospect Park West, Brooklyn, New York C...","['Warner Bros.', 'Artists Entertainment Complex']",['English'],0,20,0
3,tt0073692,Shampoo,https://www.imdb.com/title/tt0073692,1975,1h 50m,R,6.4,15K,4000000.0,49407734.0,...,"['Robert Towne', 'Warren Beatty']","['Warren Beatty', 'Julie Christie', 'Goldie Ha...","['Satire', 'Comedy', 'Drama']",['United States'],"['2270 Bowmont Drive, Beverly Hills, Californi...","['Persky-Bright / Vista', 'Columbia Pictures',...",['English'],0,11,0
4,tt0073026,Funny Lady,https://www.imdb.com/title/tt0073026,1975,2h 16m,PG,6.2,6.1K,NaN,39000000.0,...,"['Jay Presson Allen', 'Arnold Schulman']","['Barbra Streisand', 'James Caan', 'Omar Sharif']","['Biography', 'Comedy', 'Drama', 'Musical', 'R...",['United States'],"['Central Station, Oakland, California, USA']","['Columbia Pictures', 'Rastar Pictures', 'Vista']",['English'],0,0,5

### Consultar filmes ano 2024

In [20]:
query = "SELECT * FROM filmes_imdb WHERE  Year = '2024'"
df_2024 = conexao.execute(query).fetchdf()
df_2024.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt22022452,Inside Out 2,https://www.imdb.com/title/tt22022452,2024,1h 36m,PG,7.6,194K,200000000.0,1.698773e+09,...,"['Meg LeFauve', 'Dave Holstein', 'Kelsey Mann']","['Amy Poehler', 'Maya Hawke', 'Kensington Tall...","['Coming-of-Age', 'Computer Animation', 'Quest...",['United States'],['Walt Disney Feature Animation - 500 S. Buena...,"['Walt Disney Pictures', 'Pixar Animation Stud...",['English'],0,63,0
1,tt6263850,Deadpool & Wolverine,https://www.imdb.com/title/tt6263850,2024,2h 8m,R,7.6,441K,200000000.0,1.338074e+09,...,"['Ryan Reynolds', 'Rhett Reese', 'Paul Wernick']","['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin']","['Buddy Comedy', 'Dark Comedy', 'Raunchy Comed...","['United States', 'United Kingdom', 'New Zeala...","['Vancouver Film Studios - 3500 Cornett Rd, Va...","['Marvel Studios', '20th Century Studios', 'Ma...","['English', 'French', 'Spanish']",0,35,0
2,tt1262426,Wicked,https://www.imdb.com/title/tt1262426,2024,2h 40m,PG,7.9,90K,150000000.0,6.547759e+08,...,"['Winnie Holzman', 'Dana Fox', 'Gregory Maguire']","['Cynthia Erivo', 'Ariana Grande', 'Jeff Goldb...","['Fairy Tale', 'Pop Musical', 'Fantasy', 'Musi...","['United States', 'Japan', 'Canada', 'Iceland'...","['Sky Studios Elstree Rowley, Borehamwood, Her...","['Universal Pictures', 'Marc Platt Productions...",['English'],0,172,0
3,tt13622970,Moana 2,https://www.imdb.com/title/tt13622970,2024,1h 40m,PG,7.0,56K,150000000.0,9.134555e+08,...,"['Jared Bush', 'Dana Ledoux Miller', 'Bek Smith']","[""Auli'i Cravalho"", 'Dwayne Johnson', 'Hualala...","['Computer Animation', 'Sea Adventure', 'Adven...","['United States', 'Canada']","['Walt Disney Animation Studios, Vancouver BC']","['Disney Television Animation', 'The Walt Disn...",['English'],0,12,0
4,tt7510222,Despicable Me 4,https://www.imdb.com/title/tt7510222,2024,1h 34m,PG,6.2,55K,100000000.0,9.691265e+08,...,"['Mike White', 'Ken Daurio']","['Steve Carell', 'Kristen Wiig', 'Pierre Coffin']","['Computer Animation', 'Urban Adventure', 'Adv...",['United States'],None,"['Universal Pictures', 'Illumination Entertain...",['English'],0,3,0

In [30]:
df2024 = df[df['Year']== 2024]
df2024.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
8350,tt22022452,Inside Out 2,https://www.imdb.com/title/tt22022452,2024,1h 36m,PG,7.6,194K,200000000.0,1.698773e+09,...,"['Meg LeFauve', 'Dave Holstein', 'Kelsey Mann']","['Amy Poehler', 'Maya Hawke', 'Kensington Tall...","['Coming-of-Age', 'Computer Animation', 'Quest...",['United States'],['Walt Disney Feature Animation - 500 S. Buena...,"['Walt Disney Pictures', 'Pixar Animation Stud...",['English'],0,63,0
8351,tt6263850,Deadpool & Wolverine,https://www.imdb.com/title/tt6263850,2024,2h 8m,R,7.6,441K,200000000.0,1.338074e+09,...,"['Ryan Reynolds', 'Rhett Reese', 'Paul Wernick']","['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin']","['Buddy Comedy', 'Dark Comedy', 'Raunchy Comed...","['United States', 'United Kingdom', 'New Zeala...","['Vancouver Film Studios - 3500 Cornett Rd, Va...","['Marvel Studios', '20th Century Studios', 'Ma...","['English', 'French', 'Spanish']",0,35,0
8352,tt1262426,Wicked,https://www.imdb.com/title/tt1262426,2024,2h 40m,PG,7.9,90K,150000000.0,6.547759e+08,...,"['Winnie Holzman', 'Dana Fox', 'Gregory Maguire']","['Cynthia Erivo', 'Ariana Grande', 'Jeff Goldb...","['Fairy Tale', 'Pop Musical', 'Fantasy', 'Musi...","['United States', 'Japan', 'Canada', 'Iceland'...","['Sky Studios Elstree Rowley, Borehamwood, Her...","['Universal Pictures', 'Marc Platt Productions...",['English'],0,172,0
8353,tt13622970,Moana 2,https://www.imdb.com/title/tt13622970,2024,1h 40m,PG,7.0,56K,150000000.0,9.134555e+08,...,"['Jared Bush', 'Dana Ledoux Miller', 'Bek Smith']","[""Auli'i Cravalho"", 'Dwayne Johnson', 'Hualala...","['Computer Animation', 'Sea Adventure', 'Adven...","['United States', 'Canada']","['Walt Disney Animation Studios, Vancouver BC']","['Disney Television Animation', 'The Walt Disn...",['English'],0,12,0
8354,tt7510222,Despicable Me 4,https://www.imdb.com/title/tt7510222,2024,1h 34m,PG,6.2,55K,100000000.0,9.691265e+08,...,"['Mike White', 'Ken Daurio']","['Steve Carell', 'Kristen Wiig', 'Pierre Coffin']","['Computer Animation', 'Urban Adventure', 'Adv...",['United States'],None,"['Universal Pictures', 'Illumination Entertain...",['English'],0,3,0

### Consultar filmes com buget maior que 5000000

In [31]:
df_budget = df[df['budget'] > 5000000]
df_budget.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt0073195,Jaws,https://www.imdb.com/title/tt0073195,1975,2h 4m,PG,8.1,683K,7000000.0,477220580.0,...,"['Peter Benchley', 'Carl Gottlieb']","['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'...",['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...",['English'],0,20,0
9,tt0073802,Three Days of the Condor,https://www.imdb.com/title/tt0073802,1975,1h 57m,R,7.4,65K,20000000.0,27476252.0,...,"['James Grady', 'Lorenzo Semple Jr.', 'David R...","['Robert Redford', 'Faye Dunaway', 'Cliff Robe...","['Political Thriller', 'Spy', 'Crime', 'Myster...",['United States'],"['55 East 77th Street, Manhattan, New York Cit...","['Wildwood Enterprises', 'Dino De Laurentiis C...","['English', 'French']",0,4,1
10,tt0073317,Lucky Lady,https://www.imdb.com/title/tt0073317,1975,1h 58m,PG,5.2,1.4K,13000000.0,24441725.0,...,"['Willard Huyck', 'Gloria Katz']","['Gene Hackman', 'Liza Minnelli', 'Burt Reynol...","['Slapstick', 'Comedy', 'Crime', 'Drama']",['United States'],"['Guaymas, Sonora, Mexico']",['Gruskoff/Venture Films'],"['English', 'Spanish', 'French']",0,0,0
15,tt0072926,The Eiger Sanction,https://www.imdb.com/title/tt0072926,1975,2h 9m,R,6.4,23K,9000000.0,14200000.0,...,"['Hal Dresner', 'Warren Murphy', 'Rod Whitaker']","['Clint Eastwood', 'George Kennedy', 'Vonetta ...","['Action', 'Crime', 'Thriller']",['United States'],"['Zion National Park, Utah, USA']","['The Malpaso Company', 'Jennings Lang', 'Univ...","['English', 'German']",0,0,0
22,tt0072665,At Long Last Love,https://www.imdb.com/title/tt0072665,1975,1h 58m,G,5.3,1.4K,6000000.0,1500000.0,...,['Peter Bogdanovich'],"['Burt Reynolds', 'Cybill Shepherd', 'Madeline...","['Jukebox Musical', 'Romantic Comedy', 'Comedy...",['United States'],"['Los Angeles, California, USA']","['Copa del Oro', 'Twentieth Century Fox']",['English'],0,0,0

### Consultar filmes com ator vin diesel

In [ ]:
df_stars = df[df['stars'].str.contains('in diesel', case=False, na=False)]
df_stars.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
2026,tt1634106,Bloodshot,https://www.imdb.com/title/tt1634106,2020,1h 49m,PG-13,5.7,87K,45000000.0,3.986112e+07,...,"['Jeff Wadlow', 'Eric Heisserer', 'Kevin VanHo...","['Vin Diesel', 'Eiza González', 'Sam Heughan']","['Superhero', 'Action', 'Adventure', 'Sci-Fi']","['United States', 'Canada', 'South Africa', 'C...","['Montreal, Québec, Canada']","['Columbia Pictures', 'Bona Film Group', 'Anna...","['English', 'Persian']",0,7,0
3111,tt4630562,The Fate of the Furious,https://www.imdb.com/title/tt4630562,2017,2h 16m,PG-13,6.6,261K,250000000.0,1.236009e+09,...,"['Gary Scott Thompson', 'Chris Morgan']","['Vin Diesel', 'Jason Statham', 'Dwayne Johnson']","['Car Action', 'Action', 'Crime', 'Thriller']","['United States', 'China', 'Japan']","['Cleveland, Ohio, USA']","['Universal Pictures', 'China Film Co., Ltd.',...","['English', 'Russian', 'Spanish']",0,16,0
3161,tt1293847,xXx: Return of Xander Cage,https://www.imdb.com/title/tt1293847,2017,1h 47m,PG-13,5.2,99K,85000000.0,3.461183e+08,...,"['Rich Wilkes', 'F. Scott Frazier']","['Vin Diesel', 'Donnie Yen', 'Deepika Padukone']","['Action', 'Adventure', 'Thriller']","['China', 'Canada', 'United States']",['Dominican Republic'],"['Paramount Pictures', 'Revolution Studios', '...","['English', 'Spanish', 'Portuguese', 'Mandarin...",0,7,0
3655,tt1596343,Fast Five,https://www.imdb.com/title/tt1596343,2011,2h 10m,PG-13,7.3,416K,125000000.0,6.261400e+08,...,"['Chris Morgan', 'Gary Scott Thompson']","['Vin Diesel', 'Paul Walker', 'Dwayne Johnson']","['Action Epic', 'Caper', 'Car Action', 'Action...","['United States', 'Japan', 'Brazil']",['Puerto Rico'],"['Universal Pictures', 'Original Film', 'One R...","['English', 'Portuguese', 'Spanish', 'Italian'...",0,21,0
6254,tt0296572,The Chronicles of Riddick,https://www.imdb.com/title/tt0296572,2004,1h 59m,R,6.6,246K,105000000.0,1.159005e+08,...,"['Jim Wheat', 'Ken Wheat', 'David Twohy']","['Vin Diesel', 'Judi Dench', 'Colm Feore']","['Sci-Fi Epic', 'Space Sci-Fi', 'Action', 'Adv...",['United States'],"['Vancouver, British Columbia, Canada']","['Universal Pictures', 'Radar Pictures', 'One ...",['English'],0,0,0

### Pesquisar apenas filmes com origem no Canadá:

In [33]:
df_countries = df[df['countries_origin'].str.contains('Canada', case=False, na=False)]
df_countries.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
37,tt0071650,Ilsa: She Wolf of the SS,https://www.imdb.com/title/tt0071650,1975,1h 36m,R,5.1,8.4K,NaN,NaN,...,"['Jonah Royston', 'John C.W. Saxton']","['Dyanne Thorne', 'Gregory Knoph', 'Tony Mumolo']","['Drama', 'Horror', 'Thriller', 'War']",['Canada'],"['Cinema General Studios - 846 N. Cahuenga, Ho...",['Aeteas Filmproduktions'],"['English', 'German']",0,0,0
42,tt0073115,The Story of O,https://www.imdb.com/title/tt0073115,1975,1h 37m,NC-17,5.3,7.1K,NaN,NaN,...,"['Sébastien Japrisot', 'Dominique Aury']","['Corinne Cléry', 'Udo Kier', 'Anthony Steel']",['Drama'],"['France', 'West Germany', 'Canada']",None,"['A.D. Creation', 'Somerville House', 'Terra-F...","['French', 'English', 'Polish']",0,0,0
44,tt0073631,Rollerball,https://www.imdb.com/title/tt0073631,1975,2h 5m,R,6.5,30K,6000000.0,NaN,...,['William Harrison'],"['James Caan', 'John Houseman', 'Maud Adams']","['Dystopian Sci-Fi', 'Action', 'Sci-Fi', 'Sport']","['United Kingdom', 'Canada', 'United States']","['BMW Building, Munich, Bavaria, Germany']","['Algonquin', 'United Artists']",['English'],0,5,0
49,tt0073705,Shivers,https://www.imdb.com/title/tt0073705,1975,1h 27m,R,6.3,24K,185000.0,NaN,...,['David Cronenberg'],"['Paul Hampton', 'Joe Silver', 'Lynn Lowry']","['Body Horror', 'Horror', 'Sci-Fi']",['Canada'],"['200 Rue de Gaspé, Île-des-Soeurs, Montréal, ...","['Cinépix Film Properties (CFP)', 'DAL Product...","['English', 'French']",0,0,0
66,tt0072184,Snuff,https://www.imdb.com/title/tt0072184,1975,1h 20m,X,2.8,2.1K,NaN,NaN,...,"['Michael Findlay', 'Walter E. Sear']","['Margarita Amuchástegui', 'Tina Austin', 'Ana...",['Horror'],"['United States', 'Canada', 'Argentina']","['Tigre, Buenos Aires Province, Argentina']","['August Films', 'Selected Pictures']",['English'],0,0,0

### Pesquisar apenas filmes em inglês:

In [34]:
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt0073195,Jaws,https://www.imdb.com/title/tt0073195,1975,2h 4m,PG,8.1,683K,7000000.0,477220580.0,...,"['Peter Benchley', 'Carl Gottlieb']","['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'...",['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...",['English'],0,20,0
1,tt0073629,The Rocky Horror Picture Show,https://www.imdb.com/title/tt0073629,1975,1h 40m,R,7.4,173K,1200000.0,115798478.0,...,"[""Richard O'Brien"", 'Jim Sharman']","['Tim Curry', 'Susan Sarandon', 'Barry Bostwick']","['Dark Comedy', 'Raunchy Comedy', 'Rock Musica...","['United Kingdom', 'United States']","['Oakley Court, Windsor Road, Oakley Green, Wi...","['Twentieth Century Fox', 'Michael White Produ...",['English'],0,4,0
2,tt0073486,One Flew Over the Cuckoo's Nest,https://www.imdb.com/title/tt0073486,1975,2h 13m,R,8.7,1.1M,3000000.0,109115366.0,...,"['Lawrence Hauben', 'Bo Goldman', 'Ken Kesey']","['Jack Nicholson', 'Louise Fletcher', 'Michael...","['Medical Drama', 'Psychological Drama', 'Drama']",['United States'],['Oregon State Mental Hospital - 2600 Center S...,"['Fantasy Films', 'N.V. Zvaluw']",['English'],0,15,0
3,tt0072890,Dog Day Afternoon,https://www.imdb.com/title/tt0072890,1975,2h 5m,R,8.0,279K,1800000.0,50002721.0,...,"['Frank Pierson', 'P.F. Kluge', 'Thomas Moore']","['Al Pacino', 'John Cazale', 'Penelope Allen']","['Heist', 'True Crime', 'Biography', 'Crime', ...",['United States'],"['285 Prospect Park West, Brooklyn, New York C...","['Warner Bros.', 'Artists Entertainment Complex']",['English'],0,20,0
4,tt0073692,Shampoo,https://www.imdb.com/title/tt0073692,1975,1h 50m,R,6.4,15K,4000000.0,49407734.0,...,"['Robert Towne', 'Warren Beatty']","['Warren Beatty', 'Julie Christie', 'Goldie Ha...","['Satire', 'Comedy', 'Drama']",['United States'],"['2270 Bowmont Drive, Beverly Hills, Californi...","['Persky-Bright / Vista', 'Columbia Pictures',...",['English'],0,11,0

### Consultar filmes com duração superior a 2 horas

In [35]:
df_duration = df[df['Duration'] > 2]
df_duration.head()

TypeError: '>' not supported between instances of 'str' and 'int'

### Consultar filmes que tiveram uma nota maior que 6

In [36]:
df_rating = df[df['Rating'] > 6]
df_rating.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
0,tt0073195,Jaws,https://www.imdb.com/title/tt0073195,1975,2h 4m,PG,8.1,683K,7000000.0,477220580.0,...,"['Peter Benchley', 'Carl Gottlieb']","['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'...",['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...",['English'],0,20,0
1,tt0073629,The Rocky Horror Picture Show,https://www.imdb.com/title/tt0073629,1975,1h 40m,R,7.4,173K,1200000.0,115798478.0,...,"[""Richard O'Brien"", 'Jim Sharman']","['Tim Curry', 'Susan Sarandon', 'Barry Bostwick']","['Dark Comedy', 'Raunchy Comedy', 'Rock Musica...","['United Kingdom', 'United States']","['Oakley Court, Windsor Road, Oakley Green, Wi...","['Twentieth Century Fox', 'Michael White Produ...",['English'],0,4,0
2,tt0073486,One Flew Over the Cuckoo's Nest,https://www.imdb.com/title/tt0073486,1975,2h 13m,R,8.7,1.1M,3000000.0,109115366.0,...,"['Lawrence Hauben', 'Bo Goldman', 'Ken Kesey']","['Jack Nicholson', 'Louise Fletcher', 'Michael...","['Medical Drama', 'Psychological Drama', 'Drama']",['United States'],['Oregon State Mental Hospital - 2600 Center S...,"['Fantasy Films', 'N.V. Zvaluw']",['English'],0,15,0
3,tt0072890,Dog Day Afternoon,https://www.imdb.com/title/tt0072890,1975,2h 5m,R,8.0,279K,1800000.0,50002721.0,...,"['Frank Pierson', 'P.F. Kluge', 'Thomas Moore']","['Al Pacino', 'John Cazale', 'Penelope Allen']","['Heist', 'True Crime', 'Biography', 'Crime', ...",['United States'],"['285 Prospect Park West, Brooklyn, New York C...","['Warner Bros.', 'Artists Entertainment Complex']",['English'],0,20,0
4,tt0073692,Shampoo,https://www.imdb.com/title/tt0073692,1975,1h 50m,R,6.4,15K,4000000.0,49407734.0,...,"['Robert Towne', 'Warren Beatty']","['Warren Beatty', 'Julie Christie', 'Goldie Ha...","['Satire', 'Comedy', 'Drama']",['United States'],"['2270 Bowmont Drive, Beverly Hills, Californi...","['Persky-Bright / Vista', 'Columbia Pictures',...",['English'],0,11,0

### Consultar filme dos anos 2024 e 2h 40m

In [55]:
df_duration2 = df[(df['Year'] == 2024) & (df['Duration'] == '2h 40m')]
df_duration2.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
8352,tt1262426,Wicked,https://www.imdb.com/title/tt1262426,2024,2h 40m,PG,7.9,90K,150000000.0,654775945.0,...,"['Winnie Holzman', 'Dana Fox', 'Gregory Maguire']","['Cynthia Erivo', 'Ariana Grande', 'Jeff Goldb...","['Fairy Tale', 'Pop Musical', 'Fantasy', 'Musi...","['United States', 'Japan', 'Canada', 'Iceland'...","['Sky Studios Elstree Rowley, Borehamwood, Her...","['Universal Pictures', 'Marc Platt Productions...",['English'],0,172,0
8800,tt29120307,Vanvaas,https://www.imdb.com/title/tt29120307,2024,2h 40m,None,6.8,550,NaN,18172.0,...,"['Amjad Ali', 'Anil Sharma', 'Sunil Sirvaiya']","['Nana Patekar', 'Ashwini Kalsekar', 'Rajpal N...","['Action', 'Drama']",['India'],None,"['Anil Sharma Productions', 'Zee Studios']",['Hindi'],0,0,0

### Consultar filmes produzidos pela Disney

In [56]:
df_production = df[df['production_companies'].str.contains('Walt Disney Pictures', case=False, na=False)]
df_production.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
2007,tt7146812,Onward,https://www.imdb.com/title/tt7146812,2020,1h 42m,PG,7.4,176K,175000000.0,141940042.0,...,"['Dan Scanlon', 'Keith Bunin', 'Jason Headley']","['Tom Holland', 'Chris Pratt', 'Julia Louis-Dr...","['Adventure Epic', 'Computer Animation', 'Epic...","['United States', 'Japan']","['Los Angeles, California, USA']","['Walt Disney Pictures', 'Pixar Animation Stud...",['English'],0,66,1
2067,tt2948372,Soul,https://www.imdb.com/title/tt2948372,2020,1h 40m,PG,8.0,398K,NaN,121977511.0,...,"['Pete Docter', 'Mike Jones', 'Kemp Powers']","['Jamie Foxx', 'Tina Fey', 'Graham Norton']","['Computer Animation', 'Adventure', 'Animation...",['United States'],['Walt Disney Feature Animation - 500 S. Buena...,"['Walt Disney Pictures', 'Pixar Animation Stud...","['English', 'Korean', 'Inuktitut']",0,94,0
2274,tt8503618,Hamilton,https://www.imdb.com/title/tt8503618,2020,2h 40m,PG-13,8.3,124K,NaN,NaN,...,"['Lin-Manuel Miranda', 'Ron Chernow']","['Lin-Manuel Miranda', 'Phillipa Soo', 'Leslie...","['Epic', 'Biography', 'Drama', 'History', 'Mus...",['United States'],['Richard Rodgers Theatre - 226 W. 46th Street...,"['Walt Disney Pictures', '5000 Broadway Produc...","['English', 'French']",0,46,0
2294,tt4566758,Mulan,https://www.imdb.com/title/tt4566758,2020,1h 55m,PG-13,5.8,162K,200000000.0,69965374.0,...,"['Rick Jaffa', 'Amanda Silver', 'Lauren Hynek']","['Yifei Liu', 'Donnie Yen', 'Gong Li']","['Adventure Epic', 'Fantasy Epic', 'Martial Ar...","['United States', 'China']","['Kumeu Film Studios, 116 Access Road, Kumeu, ...","['Walt Disney Pictures', 'Jason T. Reed Produc...","['English', 'Mandarin']",0,42,2
2303,tt11681250,Godmothered,https://www.imdb.com/title/tt11681250,2020,1h 50m,PG,6.1,14K,NaN,NaN,...,"['Kari Granlund', 'Melissa K. Stack']","['June Squibb', 'Jillian Bell', 'Sonia Manzano']","['Fairy Tale', 'Comedy', 'Drama', 'Family', 'F...",['United States'],"['Malden, Massachusetts, USA']","['Secret Machine Entertainment', 'The Montecit...","['English', 'Latin']",0,2,0

### consultar filmes a partir de 2020

In [57]:
df_year = df[df['Year'] >= 2020]
df_year.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
2000,tt1502397,Bad Boys for Life,https://www.imdb.com/title/tt1502397,2020,2h 4m,R,6.5,187K,90000000.0,426505244.0,...,"['Peter Craig', 'Joe Carnahan', 'Chris Bremner']","['Will Smith', 'Martin Lawrence', 'Vanessa Hud...","['Buddy Cop', 'Cop Drama', 'Action', 'Comedy',...",['United States'],"['Yautepec, Morelos, Mexico']","['Columbia Pictures', '2.0 Entertainment', 'Do...","['English', 'Spanish']",0,15,0
2001,tt8332922,A Quiet Place Part II,https://www.imdb.com/title/tt8332922,2020,1h 37m,PG-13,7.2,296K,61000000.0,297372261.0,...,"['John Krasinski', 'Bryan Woods', 'Scott Beck']","['Emily Blunt', 'Millicent Simmonds', 'Cillian...","['Alien Invasion', 'Monster Horror', 'Supernat...",['United States'],"['Buffalo, New York, USA']","['Paramount Pictures', 'Platinum Dunes', 'Sund...","['English', 'American Sign Language']",0,44,1
2002,tt3794354,Sonic the Hedgehog,https://www.imdb.com/title/tt3794354,2020,1h 39m,PG,6.5,171K,85000000.0,319715683.0,...,"['Pat Casey', 'Josh Miller', 'Yuji Naka']","['Ben Schwartz', 'James Marsden', 'Jim Carrey']","['Animal Adventure', 'Buddy Comedy', 'Road Tri...","['United States', 'Japan', 'Canada', 'United K...","['Ladysmith, British Columbia, Canada']","['Paramount Pictures', 'Sega Sammy Group', 'Or...","['English', 'French', 'Persian']",0,12,0
2003,tt7713068,Birds of Prey and the Fantabulous Emancipation...,https://www.imdb.com/title/tt7713068,2020,1h 49m,R,6.1,271K,84500000.0,205537933.0,...,"['Christina Hodson', 'Paul Dini', 'Bruce Timm']","['Margot Robbie', 'Rosie Perez', 'Mary Elizabe...","['Dark Comedy', 'Superhero', 'Action', 'Comedy...","['United States', 'United Kingdom']","['Los Angeles, California, USA']","['Clubhouse Pictures (II)', 'DC Entertainment'...","['English', 'Chinese']",0,83,0
2004,tt6673612,Dolittle,https://www.imdb.com/title/tt6673612,2020,1h 41m,PG,5.6,73K,175000000.0,251410631.0,...,"['Stephen Gaghan', 'Dan Gregor', 'Doug Mand']","['Robert Downey Jr.', 'Antonio Banderas', 'Mic...","['Animal Adventure', 'Quest', 'Adventure', 'Co...","['United States', 'China', 'United Kingdom', '...","['Menai Suspension Bridge, Anglesey, Wales, UK']","['Universal Pictures', 'Perfect World Pictures...","['English', 'French']",0,9,0

### Consultar filmes a partir entre 2020 e 2024

In [ ]:
df_year2 = df[df['Year'].between(2020, 2024)]
df_year2.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
2000,tt1502397,Bad Boys for Life,https://www.imdb.com/title/tt1502397,2020,2h 4m,R,6.5,187K,90000000.0,426505244.0,...,"['Peter Craig', 'Joe Carnahan', 'Chris Bremner']","['Will Smith', 'Martin Lawrence', 'Vanessa Hud...","['Buddy Cop', 'Cop Drama', 'Action', 'Comedy',...",['United States'],"['Yautepec, Morelos, Mexico']","['Columbia Pictures', '2.0 Entertainment', 'Do...","['English', 'Spanish']",0,15,0
2001,tt8332922,A Quiet Place Part II,https://www.imdb.com/title/tt8332922,2020,1h 37m,PG-13,7.2,296K,61000000.0,297372261.0,...,"['John Krasinski', 'Bryan Woods', 'Scott Beck']","['Emily Blunt', 'Millicent Simmonds', 'Cillian...","['Alien Invasion', 'Monster Horror', 'Supernat...",['United States'],"['Buffalo, New York, USA']","['Paramount Pictures', 'Platinum Dunes', 'Sund...","['English', 'American Sign Language']",0,44,1
2002,tt3794354,Sonic the Hedgehog,https://www.imdb.com/title/tt3794354,2020,1h 39m,PG,6.5,171K,85000000.0,319715683.0,...,"['Pat Casey', 'Josh Miller', 'Yuji Naka']","['Ben Schwartz', 'James Marsden', 'Jim Carrey']","['Animal Adventure', 'Buddy Comedy', 'Road Tri...","['United States', 'Japan', 'Canada', 'United K...","['Ladysmith, British Columbia, Canada']","['Paramount Pictures', 'Sega Sammy Group', 'Or...","['English', 'French', 'Persian']",0,12,0
2003,tt7713068,Birds of Prey and the Fantabulous Emancipation...,https://www.imdb.com/title/tt7713068,2020,1h 49m,R,6.1,271K,84500000.0,205537933.0,...,"['Christina Hodson', 'Paul Dini', 'Bruce Timm']","['Margot Robbie', 'Rosie Perez', 'Mary Elizabe...","['Dark Comedy', 'Superhero', 'Action', 'Comedy...","['United States', 'United Kingdom']","['Los Angeles, California, USA']","['Clubhouse Pictures (II)', 'DC Entertainment'...","['English', 'Chinese']",0,83,0
2004,tt6673612,Dolittle,https://www.imdb.com/title/tt6673612,2020,1h 41m,PG,5.6,73K,175000000.0,251410631.0,...,"['Stephen Gaghan', 'Dan Gregor', 'Doug Mand']","['Robert Downey Jr.', 'Antonio Banderas', 'Mic...","['Animal Adventure', 'Quest', 'Adventure', 'Co...","['United States', 'China', 'United Kingdom', '...","['Menai Suspension Bridge, Anglesey, Wales, UK']","['Universal Pictures', 'Perfect World Pictures...","['English', 'French']",0,9,0

### Consultar filmes na lista de anos 2020,2021,2022,2023 e 2024

In [60]:
df_year3 = df[df['Year'].isin([2020,2021,2022,2023,2024])]
df_year3.head()

,id,Title,Movie Link,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,wins,nominations,oscars
2000,tt1502397,Bad Boys for Life,https://www.imdb.com/title/tt1502397,2020,2h 4m,R,6.5,187K,90000000.0,426505244.0,...,"['Peter Craig', 'Joe Carnahan', 'Chris Bremner']","['Will Smith', 'Martin Lawrence', 'Vanessa Hud...","['Buddy Cop', 'Cop Drama', 'Action', 'Comedy',...",['United States'],"['Yautepec, Morelos, Mexico']","['Columbia Pictures', '2.0 Entertainment', 'Do...","['English', 'Spanish']",0,15,0
2001,tt8332922,A Quiet Place Part II,https://www.imdb.com/title/tt8332922,2020,1h 37m,PG-13,7.2,296K,61000000.0,297372261.0,...,"['John Krasinski', 'Bryan Woods', 'Scott Beck']","['Emily Blunt', 'Millicent Simmonds', 'Cillian...","['Alien Invasion', 'Monster Horror', 'Supernat...",['United States'],"['Buffalo, New York, USA']","['Paramount Pictures', 'Platinum Dunes', 'Sund...","['English', 'American Sign Language']",0,44,1
2002,tt3794354,Sonic the Hedgehog,https://www.imdb.com/title/tt3794354,2020,1h 39m,PG,6.5,171K,85000000.0,319715683.0,...,"['Pat Casey', 'Josh Miller', 'Yuji Naka']","['Ben Schwartz', 'James Marsden', 'Jim Carrey']","['Animal Adventure', 'Buddy Comedy', 'Road Tri...","['United States', 'Japan', 'Canada', 'United K...","['Ladysmith, British Columbia, Canada']","['Paramount Pictures', 'Sega Sammy Group', 'Or...","['English', 'French', 'Persian']",0,12,0
2003,tt7713068,Birds of Prey and the Fantabulous Emancipation...,https://www.imdb.com/title/tt7713068,2020,1h 49m,R,6.1,271K,84500000.0,205537933.0,...,"['Christina Hodson', 'Paul Dini', 'Bruce Timm']","['Margot Robbie', 'Rosie Perez', 'Mary Elizabe...","['Dark Comedy', 'Superhero', 'Action', 'Comedy...","['United States', 'United Kingdom']","['Los Angeles, California, USA']","['Clubhouse Pictures (II)', 'DC Entertainment'...","['English', 'Chinese']",0,83,0
2004,tt6673612,Dolittle,https://www.imdb.com/title/tt6673612,2020,1h 41m,PG,5.6,73K,175000000.0,251410631.0,...,"['Stephen Gaghan', 'Dan Gregor', 'Doug Mand']","['Robert Downey Jr.', 'Antonio Banderas', 'Mic...","['Animal Adventure', 'Quest', 'Adventure', 'Co...","['United States', 'China', 'United Kingdom', '...","['Menai Suspension Bridge, Anglesey, Wales, UK']","['Universal Pictures', 'Perfect World Pictures...","['English', 'French']",0,9,0

In [ ]:

# SELECT * from filmes_imdb fi
# where production_companies like '%Universal Pictures%'
# and countries_origin like '%United States%'
df_languages = df[df['Languages'].isin('English', case=False, na=False)]
df_languages.head()

# SELECT Title,"Year", Languages,Rating
# FROM filmes_imdb fi
# WHERE "Year" IN(2020,2021,2022,2023,2024)
# ORDER BY Rating
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()

# SELECT
# 	"Year",
# 	count(*) quantidade,
# 	sum(Rating) total_rating,
# 	avg(Rating) media_rating,
# 	ROUND(avg(Rating),2) media_formata
# FROM filmes_imdb fi
# WHERE "Year" IN(2020,2021,2022,2023,2024)
# GROUP BY "Year"
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()

# SELECT
# 	"Year",
# 	count(*) quantidade,
# 	sum(Rating) total_rating,
# 	avg(Rating) media_rating,
# 	ROUND(avg(Rating),2) media_formata
# FROM filmes_imdb fi
# WHERE "Year" NOT IN(2020,2021,2022,2023,2024)
# GROUP BY "Year"
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()

# SELECT
# 	budget,
# 	grossWorldWide,
# 	gross_US_Canada,
# 	(grossWorldWide + gross_US_Canada)  gross,
# 	ROUND( grossWorldWide / budget,2) as tickt
# FROM filmes_imdb fi
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()

# SELECT
# 	UPPER(title) maiusculo,
# 	LOWER(title) minusculo
# FROM filmes_imdb fi
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()

# SELECT * FROM filmes_imdb
# WHERE writers LIKE '%Varda%'

# -- Consultar filmes brasileiros lançados
# -- nos anos que teve Copa do Mundo
# SELECT * FROM filmes_imdb fi
# WHERE "Year" IN (
# 	SELECT DISTINCT YEAR
# 	FROM filmes_imdb
# 	WHERE ((YEAR+2)%4) = 0 --
# 	)
# AND countries_origin LIKE '%Brazil%'
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()



# SELECT
# 	fi.id,
# 	fi.stars,
# 	fi.genres,
# 	g.id,
# 	s.id
# FROM filmes_imdb fi
# INNER JOIN genres g ON fi.genres = g.genres
# INNER JOIN stars s ON fi.stars = s.stars
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()


# SELECT
# 	fi.id,
# 	fi.stars,
# 	fi.genres,
# 	g.id,
# 	s.id
# FROM filmes_imdb fi
# INNER JOIN genres g ON fi.genres = g.genres
# INNER JOIN stars s ON fi.stars = s.stars
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()


# SELECT
# DISTINCT genres
# FROM filmes_imdb
# WHERE genres IS NOT NULL
# AND genres <> "['Drama', 'Romance']"
df_languages = df[df['Languages'].str.contains('English', case=False, na=False)]
df_languages.head()


# /*
# Detalhes básicos do filme: título, ano, duração, classificação MPA, classificação IMDb, votos.
# Dados financeiros: Orçamento, bruto global, bruto dos EUA/Canadá, ganhos do fim de semana de abertura.
# Créditos: Diretores, roteiristas, estrelas.
# Detalhes adicionais: gêneros, países, locais de filmagem, produtoras, idiomas.
# Prêmios: Vitórias, indicações, indicações ao Oscar.
# */

In [61]:
# Fechar a conexão
conexao.close()

print("Dados importados com sucesso para o banco de dados SQLite.")

Dados importados com sucesso para o banco de dados SQLite.